import type { Muscle } from "@/lib/referentiels/muscles";
import type { Equipement } from "@/lib/referentiels/equipements";

/**
 * Catalogue d'exercices.
 *
 * Curation de la bibliotheque workout-guide (302 exercices) restreinte a ce qui
 * est pertinent en salle : materiel charge, hypertrophie. Le pilier, le profil de
 * tension et la categorie de role n'existent pas dans la bibliotheque source —
 * ils ont ete attribues manuellement, exercice par exercice.
 *
 * Les illustrations sont dans public/exercices/<slug>/frame-<n>.svg, copiees
 * verbatim depuis la bibliotheque. Voir CREDITS dans le README (CC BY-SA 4.0).
 *
 * Genere puis maintenu a la main. Ne pas regenerer sans reporter les corrections.
 */

export interface ExerciceCatalogue {
  slug: string;
  nom: string;
  pilier: string;
  profilTension: "stretch" | "mi_range" | "contract";
  categorieRole: "pilier" | "substitut" | "accessoire";
  type: "polyarticulaire" | "isolation";
  equipement: Equipement;
  musclesPrincipaux: Muscle[];
  musclesSecondaires: Muscle[];
  nbFrames: number;
}

export const CATALOGUE: ExerciceCatalogue[] = [
  {
    slug: "bench-press",
    nom: "Bench Press",
    pilier: "P1_poussee",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "cable-fly",
    nom: "Cable Fly",
    pilier: "P1_poussee",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "chest-dip",
    nom: "Chest Dip",
    pilier: "P1_poussee",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "decline-bench-press",
    nom: "Decline Bench Press",
    pilier: "P1_poussee",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "dumbbell-bench-press",
    nom: "Dumbbell Bench Press",
    pilier: "P1_poussee",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "dumbbell-fly",
    nom: "Dumbbell Fly",
    pilier: "P1_poussee",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "incline-bench-press",
    nom: "Incline Bench Press",
    pilier: "P1_poussee",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "incline-cable-fly",
    nom: "Incline Cable Fly",
    pilier: "P1_poussee",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "incline-dumbbell-press",
    nom: "Incline Dumbbell Press",
    pilier: "P1_poussee",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "machine-chest-press",
    nom: "Machine Chest Press",
    pilier: "P1_poussee",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "pec-deck",
    nom: "Pec Deck",
    pilier: "P1_poussee",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "push-up",
    nom: "Push-up",
    pilier: "P1_poussee",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["core", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "smith-machine-bench-press",
    nom: "Smith Machine Bench Press",
    pilier: "P1_poussee",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["pectoraux"],
    musclesSecondaires: ["epaules", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "weighted-dip",
    nom: "Weighted Dip",
    pilier: "P1_poussee",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules", "pectoraux"],
    nbFrames: 3,
  },
  {
    slug: "barbell-row",
    nom: "Barbell Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps", "deltoide_posterieur"],
    nbFrames: 3,
  },
  {
    slug: "shrug",
    nom: "Barbell Shrug",
    pilier: "P2_tirage",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "barre",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "chest-supported-row",
    nom: "Chest Supported Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps", "deltoide_posterieur"],
    nbFrames: 3,
  },
  {
    slug: "chin-up",
    nom: "Chin-up",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["dorsaux"],
    nbFrames: 3,
  },
  {
    slug: "close-grip-lat-pulldown",
    nom: "Close-Grip Lat Pulldown",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["dorsaux"],
    musclesSecondaires: ["biceps"],
    nbFrames: 3,
  },
  {
    slug: "dumbbell-bent-over-row",
    nom: "Dumbbell Bent Over Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps", "deltoide_posterieur"],
    nbFrames: 3,
  },
  {
    slug: "dumbbell-shrug",
    nom: "Dumbbell Shrug",
    pilier: "P2_tirage",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "inverted-row",
    nom: "Inverted Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps", "core"],
    nbFrames: 3,
  },
  {
    slug: "lat-pulldown",
    nom: "Lat Pulldown",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["dorsaux"],
    musclesSecondaires: ["biceps"],
    nbFrames: 3,
  },
  {
    slug: "machine-row",
    nom: "Machine Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps"],
    nbFrames: 3,
  },
  {
    slug: "neutral-grip-pull-up",
    nom: "Neutral-Grip Pull-up",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["dorsaux"],
    musclesSecondaires: ["biceps", "core"],
    nbFrames: 3,
  },
  {
    slug: "one-arm-dumbbell-row",
    nom: "One-Arm Dumbbell Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps"],
    nbFrames: 3,
  },
  {
    slug: "pendlay-row",
    nom: "Pendlay Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps", "deltoide_posterieur"],
    nbFrames: 3,
  },
  {
    slug: "pull-up",
    nom: "Pull-up",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["dorsaux"],
    musclesSecondaires: ["biceps", "core"],
    nbFrames: 3,
  },
  {
    slug: "seated-row",
    nom: "Seated Cable Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps", "deltoide_posterieur"],
    nbFrames: 3,
  },
  {
    slug: "single-arm-cable-row",
    nom: "Single-Arm Cable Row",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps", "deltoide_posterieur"],
    nbFrames: 3,
  },
  {
    slug: "straight-arm-pulldown",
    nom: "Straight-Arm Pulldown",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["dorsaux"],
    musclesSecondaires: ["core"],
    nbFrames: 3,
  },
  {
    slug: "t-bar-row",
    nom: "T-Bar Row",
    pilier: "P2_tirage",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["biceps", "deltoide_posterieur"],
    nbFrames: 3,
  },
  {
    slug: "weighted-pull-up",
    nom: "Weighted Pull-up",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["dorsaux"],
    musclesSecondaires: ["biceps"],
    nbFrames: 3,
  },
  {
    slug: "wide-grip-lat-pulldown",
    nom: "Wide-Grip Lat Pulldown",
    pilier: "P2_tirage",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["dorsaux"],
    musclesSecondaires: ["biceps"],
    nbFrames: 3,
  },
  {
    slug: "belt-squat",
    nom: "Belt Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["fessiers"],
    nbFrames: 3,
  },
  {
    slug: "bulgarian-split-squat",
    nom: "Bulgarian Split Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "front-squat",
    nom: "Front Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "front-foot-elevated-split-squat",
    nom: "Front-Foot Elevated Split Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "goblet-squat",
    nom: "Goblet Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "hack-squat",
    nom: "Hack Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["fessiers"],
    nbFrames: 3,
  },
  {
    slug: "heel-elevated-goblet-squat",
    nom: "Heel-Elevated Goblet Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "leg-press",
    nom: "Leg Press",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["fessiers", "ischios"],
    nbFrames: 3,
  },
  {
    slug: "reverse-lunge",
    nom: "Reverse Lunge",
    pilier: "P3_squat",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["fessiers", "ischios"],
    nbFrames: 3,
  },
  {
    slug: "smith-machine-squat",
    nom: "Smith Machine Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "split-squat",
    nom: "Split Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "squat",
    nom: "Squat",
    pilier: "P3_squat",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "step-up",
    nom: "Step-Up",
    pilier: "P3_squat",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["fessiers"],
    nbFrames: 3,
  },
  {
    slug: "walking-lunge",
    nom: "Walking Lunge",
    pilier: "P3_squat",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: ["fessiers", "ischios"],
    nbFrames: 3,
  },
  {
    slug: "back-extension",
    nom: "Back Extension",
    pilier: "P4_hanche",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["lombaires"],
    musclesSecondaires: ["fessiers", "ischios"],
    nbFrames: 3,
  },
  {
    slug: "barbell-glute-bridge",
    nom: "Barbell Glute Bridge",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["core", "ischios"],
    nbFrames: 3,
  },
  {
    slug: "cable-kickback",
    nom: "Cable Kickback",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["ischios"],
    nbFrames: 3,
  },
  {
    slug: "cable-pull-through",
    nom: "Cable Pull-Through",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["ischios", "lombaires"],
    nbFrames: 3,
  },
  {
    slug: "deadlift",
    nom: "Deadlift",
    pilier: "P4_hanche",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["avant_bras", "haut_dos"],
    nbFrames: 3,
  },
  {
    slug: "dumbbell-hip-thrust",
    nom: "Dumbbell Hip Thrust",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["ischios"],
    nbFrames: 3,
  },
  {
    slug: "dumbbell-romanian-deadlift",
    nom: "Dumbbell Romanian Deadlift",
    pilier: "P4_hanche",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["fessiers", "lombaires"],
    nbFrames: 3,
  },
  {
    slug: "glute-focused-back-extension",
    nom: "Glute-Focused Back Extension",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["ischios", "lombaires"],
    nbFrames: 3,
  },
  {
    slug: "good-morning",
    nom: "Good Morning",
    pilier: "P4_hanche",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["fessiers", "lombaires"],
    nbFrames: 3,
  },
  {
    slug: "hip-abduction-machine",
    nom: "Hip Abduction Machine",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["core"],
    nbFrames: 3,
  },
  {
    slug: "hip-adduction-machine",
    nom: "Hip Adduction Machine",
    pilier: "P4_hanche",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["adducteurs"],
    musclesSecondaires: ["core"],
    nbFrames: 3,
  },
  {
    slug: "hip-thrust",
    nom: "Hip Thrust",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["ischios"],
    nbFrames: 3,
  },
  {
    slug: "kettlebell-swing",
    nom: "Kettlebell Swing",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "kettlebell",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["core", "ischios"],
    nbFrames: 3,
  },
  {
    slug: "machine-glute-kickback",
    nom: "Machine Glute Kickback",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["ischios"],
    nbFrames: 3,
  },
  {
    slug: "romanian-deadlift",
    nom: "Romanian Deadlift",
    pilier: "P4_hanche",
    profilTension: "stretch",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["fessiers", "lombaires"],
    nbFrames: 3,
  },
  {
    slug: "single-leg-romanian-deadlift",
    nom: "Single-Leg Romanian Deadlift",
    pilier: "P4_hanche",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["core", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "smith-machine-hip-thrust",
    nom: "Smith Machine Hip Thrust",
    pilier: "P4_hanche",
    profilTension: "contract",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["fessiers"],
    musclesSecondaires: ["core", "ischios"],
    nbFrames: 3,
  },
  {
    slug: "smith-machine-romanian-deadlift",
    nom: "Smith Machine Romanian Deadlift",
    pilier: "P4_hanche",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["fessiers", "lombaires"],
    nbFrames: 3,
  },
  {
    slug: "sumo-deadlift",
    nom: "Sumo Deadlift",
    pilier: "P4_hanche",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["fessiers", "quadriceps"],
    nbFrames: 3,
  },
  {
    slug: "trap-bar-deadlift",
    nom: "Trap Bar Deadlift",
    pilier: "P4_hanche",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["avant_bras", "quadriceps"],
    nbFrames: 3,
  },
  {
    slug: "bicep-curl",
    nom: "Bicep Curl",
    pilier: "bras_biceps",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "cable-curl",
    nom: "Cable Curl",
    pilier: "bras_biceps",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "concentration-curl",
    nom: "Concentration Curl",
    pilier: "bras_biceps",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "ez-bar-curl",
    nom: "EZ-Bar Curl",
    pilier: "bras_biceps",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "barre",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "hammer-curl",
    nom: "Hammer Curl",
    pilier: "bras_biceps",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "incline-dumbbell-curl",
    nom: "Incline Dumbbell Curl",
    pilier: "bras_biceps",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "preacher-curl",
    nom: "Preacher Curl",
    pilier: "bras_biceps",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "reverse-curl",
    nom: "Reverse Curl",
    pilier: "bras_biceps",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "barre",
    musclesPrincipaux: ["avant_bras"],
    musclesSecondaires: ["biceps"],
    nbFrames: 3,
  },
  {
    slug: "rope-hammer-curl",
    nom: "Rope Hammer Curl",
    pilier: "bras_biceps",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "spider-curl",
    nom: "Spider Curl",
    pilier: "bras_biceps",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["biceps"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "bench-dip",
    nom: "Bench Dip",
    pilier: "bras_triceps",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules", "pectoraux"],
    nbFrames: 3,
  },
  {
    slug: "close-grip-bench-press",
    nom: "Close-Grip Bench Press",
    pilier: "bras_triceps",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules", "pectoraux"],
    nbFrames: 3,
  },
  {
    slug: "dip",
    nom: "Dip",
    pilier: "bras_triceps",
    profilTension: "stretch",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules", "pectoraux"],
    nbFrames: 3,
  },
  {
    slug: "dumbbell-overhead-tricep-extension",
    nom: "Dumbbell Overhead Tricep Extension",
    pilier: "bras_triceps",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "overhead-tricep-extension",
    nom: "Overhead Tricep Extension",
    pilier: "bras_triceps",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "rope-tricep-pushdown",
    nom: "Rope Tricep Pushdown",
    pilier: "bras_triceps",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "skull-crusher",
    nom: "Skull Crusher",
    pilier: "bras_triceps",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "barre",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "tricep-kickback",
    nom: "Tricep Kickback",
    pilier: "bras_triceps",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "tricep-pushdown",
    nom: "Tricep Pushdown",
    pilier: "bras_triceps",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "dumbbell-skull-crusher",
    nom: "Two Dumbbell Skullcrusher",
    pilier: "bras_triceps",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["triceps"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "ab-wheel",
    nom: "Ab Wheel Rollout",
    pilier: "core",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["core"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "cable-crunch",
    nom: "Cable Crunch",
    pilier: "core",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["core"],
    musclesSecondaires: [],
    nbFrames: 3,
  },
  {
    slug: "cable-woodchop",
    nom: "Cable Woodchop",
    pilier: "core",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["core"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "dead-bug",
    nom: "Dead Bug",
    pilier: "core",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["core"],
    musclesSecondaires: ["quadriceps"],
    nbFrames: 3,
  },
  {
    slug: "half-kneeling-pallof-press",
    nom: "Half-Kneeling Pallof Press",
    pilier: "core",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["core"],
    musclesSecondaires: ["epaules", "fessiers"],
    nbFrames: 3,
  },
  {
    slug: "hanging-leg-raise",
    nom: "Hanging Leg Raise",
    pilier: "core",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["core"],
    musclesSecondaires: ["avant_bras"],
    nbFrames: 3,
  },
  {
    slug: "pallof-press",
    nom: "Pallof Press",
    pilier: "core",
    profilTension: "mi_range",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["core"],
    musclesSecondaires: ["epaules"],
    nbFrames: 3,
  },
  {
    slug: "weighted-crunch",
    nom: "Weighted Crunch",
    pilier: "core",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "disque",
    musclesPrincipaux: ["core"],
    musclesSecondaires: [],
    nbFrames: 3,
  },
  {
    slug: "arnold-press",
    nom: "Arnold Press",
    pilier: "epaules",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["triceps"],
    nbFrames: 3,
  },
  {
    slug: "cable-front-raise",
    nom: "Cable Front Raise",
    pilier: "epaules",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["pectoraux"],
    nbFrames: 3,
  },
  {
    slug: "cable-lateral-raise",
    nom: "Cable Lateral Raise",
    pilier: "epaules",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["haut_dos"],
    nbFrames: 3,
  },
  {
    slug: "cable-rear-delt-fly",
    nom: "Cable Rear Delt Fly",
    pilier: "epaules",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poulie",
    musclesPrincipaux: ["deltoide_posterieur"],
    musclesSecondaires: ["haut_dos"],
    nbFrames: 3,
  },
  {
    slug: "seated-dumbbell-press",
    nom: "Dumbbell Seated Shoulder Press",
    pilier: "epaules",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["triceps"],
    nbFrames: 3,
  },
  {
    slug: "face-pull",
    nom: "Face Pull",
    pilier: "epaules",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "polyarticulaire",
    equipement: "poulie",
    musclesPrincipaux: ["haut_dos"],
    musclesSecondaires: ["deltoide_posterieur", "epaules"],
    nbFrames: 3,
  },
  {
    slug: "front-raise",
    nom: "Front Raise",
    pilier: "epaules",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["pectoraux"],
    nbFrames: 3,
  },
  {
    slug: "landmine-press",
    nom: "Landmine Press",
    pilier: "epaules",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["pectoraux", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "lateral-raise",
    nom: "Lateral Raise",
    pilier: "epaules",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["haut_dos"],
    nbFrames: 3,
  },
  {
    slug: "machine-lateral-raise",
    nom: "Machine Lateral Raise",
    pilier: "epaules",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["haut_dos"],
    nbFrames: 3,
  },
  {
    slug: "machine-shoulder-press",
    nom: "Machine Shoulder Press",
    pilier: "epaules",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "machine",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["triceps"],
    nbFrames: 3,
  },
  {
    slug: "overhead-press",
    nom: "Overhead Press",
    pilier: "epaules",
    profilTension: "mi_range",
    categorieRole: "pilier",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["triceps"],
    nbFrames: 3,
  },
  {
    slug: "push-press",
    nom: "Push Press",
    pilier: "epaules",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "barre",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["quadriceps", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "rear-delt-fly",
    nom: "Rear Delt Fly",
    pilier: "epaules",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "halteres",
    musclesPrincipaux: ["deltoide_posterieur"],
    musclesSecondaires: ["haut_dos"],
    nbFrames: 3,
  },
  {
    slug: "reverse-pec-deck",
    nom: "Reverse Pec Deck",
    pilier: "epaules",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["deltoide_posterieur"],
    musclesSecondaires: ["haut_dos"],
    nbFrames: 3,
  },
  {
    slug: "standing-dumbbell-press",
    nom: "Standing Dumbbell Press",
    pilier: "epaules",
    profilTension: "mi_range",
    categorieRole: "substitut",
    type: "polyarticulaire",
    equipement: "halteres",
    musclesPrincipaux: ["epaules"],
    musclesSecondaires: ["core", "triceps"],
    nbFrames: 3,
  },
  {
    slug: "leg-curl",
    nom: "Leg Curl",
    pilier: "jambes_iso",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["mollets"],
    nbFrames: 3,
  },
  {
    slug: "leg-extension",
    nom: "Leg Extension",
    pilier: "jambes_iso",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["quadriceps"],
    musclesSecondaires: [],
    nbFrames: 3,
  },
  {
    slug: "leg-press-calf-raise",
    nom: "Leg Press Calf Raise",
    pilier: "jambes_iso",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["mollets"],
    musclesSecondaires: [],
    nbFrames: 3,
  },
  {
    slug: "lying-leg-curl",
    nom: "Lying Leg Curl",
    pilier: "jambes_iso",
    profilTension: "contract",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["mollets"],
    nbFrames: 3,
  },
  {
    slug: "nordic-hamstring-curl",
    nom: "Nordic Hamstring Curl",
    pilier: "jambes_iso",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "poids_du_corps",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["fessiers", "mollets"],
    nbFrames: 3,
  },
  {
    slug: "seated-calf-raise",
    nom: "Seated Calf Raise",
    pilier: "jambes_iso",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["mollets"],
    musclesSecondaires: [],
    nbFrames: 3,
  },
  {
    slug: "seated-leg-curl",
    nom: "Seated Leg Curl",
    pilier: "jambes_iso",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["ischios"],
    musclesSecondaires: ["mollets"],
    nbFrames: 3,
  },
  {
    slug: "standing-calf-raise",
    nom: "Standing Calf Raise",
    pilier: "jambes_iso",
    profilTension: "stretch",
    categorieRole: "accessoire",
    type: "isolation",
    equipement: "machine",
    musclesPrincipaux: ["mollets"],
    musclesSecondaires: [],
    nbFrames: 3,
  },
];

/** Chemin public d'une frame d'illustration (1-indexee). */
export function urlIllustration(slug: string, frame = 1): string {
  return `/exercices/${slug}/frame-${frame}.svg`;
}

export const CATALOGUE_PAR_SLUG = new Map(CATALOGUE.map((e) => [e.slug, e]));
